Feature split job
aaronang/cong-the-ripper pull request #16
Opened 2016-10-21 14:01 UTC by kc1212

The basic idea is: first we convert the binary string into a number that has a base with respect to the character set. Then we perform arithmetic on that number to do the chunking. 

I also changed the types to match what is used in https://godoc.org/golang.org/x/crypto/pbkdf2

fixes #5

2016-10-21 19:59 UTC, aaronang reviewed
Before I start looking at the code, I need more context for the terminology used.

2016-10-21 19:59 UTC, aaronang commented on lib/common.go
> +type Job struct {
Don't forget to remove the `Job` definition in `master/server.go`.

2016-10-21 19:59 UTC, aaronang commented on lib/common.go
> +type CharSet int
I just thought that `CharSet` might not be the right name. In fact, charset normally indicates stuff like UTF-8 and such. Maybe just `Chars`?

2016-10-21 19:59 UTC, aaronang commented on lib/common.go
> +	Job
Are we able to find the belonging job this way? If eventually a task would finish, how could we find the belonging job? Do we need a `JobID` here?

2016-10-21 19:59 UTC, aaronang commented on master/job.go
> +	nums := "0123456789"
Shouldn't all these _character sets_ be `const`? They shouldn't be allowed to change right?

2016-10-21 19:59 UTC, aaronang commented on master/job.go
> +// SplitJob attempts to split a cracking job into equal sized tasks
What do we define with equal here? Equal size to all tasks within a job, or equal size with **all** tasks regardless to which job it belongs?

2016-10-21 19:59 UTC, aaronang commented on master/job.go
> +	Tasks []lib.Task
Why is `Tasks` capitalized and `id` not?

2016-10-21 19:59 UTC, aaronang commented on master/job.go
> +// SplitJob attempts to split a cracking job into equal sized tasks
What does `size` represent as an argument? It is not clear to me what it means. For example, what does it mean if `size = 10` is passed as an argument?

2016-10-21 20:16 UTC, kc1212 commented
@aaronang I address all those issues except the `CharSet` one, I think `Chars` is a bit too general, but if I can't think of anything else then we'll probably just use `Chars`.

2016-10-21 20:49 UTC, kc1212 commented
I'm proposing the following - from my benchmarks, `countUntilFinal` is slow, making `chunkCharSet` also slow. Which puts a lot of load on the master (`t2.micro` will be even slower than my laptop). So I'm proposing to change
```Go
type Task struct {
	Job
	JobID   int
	ID      int
	Start   []byte
	TaskLen int
}
```
to 
```Go
type Task struct {
	Job
	JobID   int
	ID      int
	Start   []byte
	FinalTask bool
}
```

The `TaskLen` will be a constant variable, known to both the master and the slave at compile time. The slave will run the brute force starting at the candidate byte slice `Start` for `TaskLen` rounds if `FinalTask` is false, otherwise it will run until the final candidate byte slice. Thoughts @aaronang @victor-li ? This will impact your brute force library @victor-li.

2016-10-21 21:04 UTC, victor-li commented
I do not think that a fixed length is a good idea. If your size is for example `possibleChars`^4, then an 4 character password job would contain 1 task, but an 7 character password job would already contain 1000 tasks. Because it grows exponentially for every extra character, we might need to think of an other algorithm to handle this with an dynamic size.

Also, in your proposal, the `FinalTask` field is not necessary, because the cracker would be able to figure that out by checking the carry after the increment of []int.

2016-10-21 21:11 UTC, victor-li requested changes
It would be nice if the constants and the methods `bytesToIntSlice`, `addToIntSlice`, and `intSliceToBytes` could be moved to a generic util class, since I also need this for the brute-forcer

2016-10-21 21:11 UTC, victor-li commented on master/job.go
> +	charSetSlice = [][]byte{
Maybe it is a better idea to put the constants in the lib, since I also need them for the brute-forcer

2016-10-21 21:16 UTC, kc1212 commented
The task sizes indeed grows exponentially, but our load balancing approach is built on the assumption that tasks are fixed size. So if we're throwing that assumption away then we need to rethink about load balancing.

For this particular project, I don't think we're able to crack anything that's higher than 6 characters, there are only 20 t2.micro and every round of PBKDF2 needs thousands of hashes. So there isn't much room for the jobs to grow.

Regarding the `FinalTask`, I put it there because I thought it'll slow down the cracker down if there's an if-statement inside the brute force loop checking for the final carry. But this just my premature optimisation, one if statement is negligible compared to 1000s of SHA2.

2016-10-21 21:17 UTC, kc1212 commented on master/job.go
> +	charSetSlice = [][]byte{
will do

2016-10-21 21:24 UTC, victor-li commented
I agree with the maximum length of 6 for this project, but we will see how well the cluster performs we get it running.

I am fine with the `FinalTask` field, because it indeed will "improve" the performance of the cracker. However, I think there should be some check to find out if an overflow occurred during incrementing. But if the master correctly calculates the offsets, it should not overflow at the slave.

2016-10-21 22:04 UTC, kc1212 commented
@victor-li Moved the functions to common, and I'll keep the code like this for now, without adding `FinalTask` and keeping `TaskLen` in the `Task` struct. We'll update the current implementation if necessary after we have a better idea of what the cracker will look like.

2016-10-21 22:05 UTC, kc1212 commented on lib/common.go
> +	Job
I added a `JobID`

2016-10-21 22:08 UTC, kc1212 commented on lib/common.go
> +type CharSet int
I think the correct term is `Alphabet`, but that might be a bit confusing since the enums are like `AlphaLower` etc. OTOH, this is a type while `AlphaLower` are consts. I think `Alphabet` is an improvement over `CharSet`  and `Chars`.

2016-10-22 14:51 UTC, aaronang commented
I don't think we necessary have to stick with t2.micro; we have $150 dollar left, no need to save money for now :stuck_out_tongue:

2016-10-22 16:18 UTC, aaronang reviewed
`AddToIntSlice` took ages to understand. This means that code readability can be improved. Just not sure if we should focus on it right now as it seems to do its job fine.

2016-10-22 16:18 UTC, aaronang commented on lib/common.go
> +type CharSet int
I agree, `Alphabet` is also used in automata theory. Would be nice if you change every name according to this convention.

2016-10-22 16:18 UTC, aaronang commented on lib/common.go
> +func TestEqInts(a, b []int) bool {
Would it better to replace this with [`reflect.DeepEqual`](https://golang.org/pkg/reflect/#DeepEqual)?

2016-10-22 16:18 UTC, aaronang commented on lib/common.go
> +var CharSetSlice [][]byte
Accordingly, I think a good name would be: `Alphabets`. No need for the variable name to also indicates its underlying type.

2016-10-22 16:18 UTC, aaronang commented on master/job.go
> +func initialCandidate(charset lib.CharSet, l int) []byte {
Does it make sense to ask the receiver (`*Alphabet`) for its initial candidates? All functions that take `*Alphabet` as first argument could then be made into an `Alphabet` library that deals with creating candidates?

2016-10-22 16:18 UTC, aaronang commented on master/job.go
> +	var ints []int
I think it makes sense to call this `lens` just as in `SplitJob`.

2016-10-22 16:18 UTC, aaronang commented on master/job.go
> +			// this part is not efficient, if the worker has the ability to run
Improving this part seems is premature optimization to me. It is only computed once for every job submission, shouldn't be a too big of a problem right?

2016-10-22 16:38 UTC, kc1212 commented on master/job.go
> +			// this part is not efficient, if the worker has the ability to run
It's not premature optimisation because it is already evident that this is a bottle neck. It's taking 0.1 seconds on `chunkCharSet(lib.AlphaNumLower, 6, 1024*1024)`, without using `countUntilFinal` it is only 0.001 seconds. Thus if jobs are arriving close to the rate of 10/second then the master is not going to cope. If the brute force library knows when it has reached the end efficiently, then we won't need to use `countUntilFinal`. I will change it accordingly when the brute force library is in place.

2016-10-22 17:47 UTC, aaronang commented on master/job.go
> +			// this part is not efficient, if the worker has the ability to run
Can't we just use base 10 to do the computations?

2016-10-22 18:04 UTC, kc1212 commented on lib/common.go
> +func TestEqInts(a, b []int) bool {
I'm keeping the `TestEqInts`. Using `reflect.DeepEqual` caused `job_test.go` to jump from 0.12 seconds to 0.5 seconds.

2016-10-22 18:05 UTC, kc1212 commented
@aaronang Hopefully d24fc5b addressed all the comments that I didn't respond to

2016-10-22 18:15 UTC, kc1212 commented on master/job.go
> +			// this part is not efficient, if the worker has the ability to run
Yes, that's why I suggested to use math/big. Normal ints won't be able to handle long candidate passwords. We could use int64, it'll be enough for this project. But for passwords of length 10ish or more then you need a bignum library.

2016-10-22 18:31 UTC, kc1212 commented on master/job.go
> +			// this part is not efficient, if the worker has the ability to run
Just computed: if we use mixed case alphanumerical (62 alphabets), then int64/uint64 will support no more than 10 characters.

2016-10-22 19:07 UTC, aaronang commented on master/job.go
> +			// this part is not efficient, if the worker has the ability to run
I see, what if we just start using the `math/big`? Is it easy to change to this?

2016-10-22 19:13 UTC, aaronang reviewed
@kc1212 Is it easy for you to benchmark `math/big`? Or do you think that just using `int` for now does the job?

2016-10-22 19:13 UTC, aaronang commented on lib/common.go
> +func BytesToIntSlice(charset Alphabet, inp []byte) []int {
Just nitpicking, `charset` should be `alph`.

2016-10-22 19:19 UTC, aaronang commented on lib/common.go
> +func (alph Alphabet) InitialCandidate(l int) []byte {
I think we should decide on convention whether to use pointer receivers or value receivers. Although, I think pointer receiver is nicer since it allows the user to both pointer and value to call the method. For more reference, https://stackoverflow.com/questions/27775376/value-receiver-vs-pointer-receiver-in-golang.

2016-10-22 19:23 UTC, kc1212 commented on lib/common.go
> +func (alph Alphabet) InitialCandidate(l int) []byte {
If you use pointer receiver you can't write `AlphaLower.InitialCandidate`. That's why I went with value receiver.

From that reference:

If the receiver is a small array or struct that is naturally a value type (for instance, something like the time.Time type), with no mutable fields and no pointers, or is just a simple basic type such as int or string, a value receiver makes sense.

2016-10-22 19:27 UTC, kc1212 commented
I'll change to bignum/int when it is necessary. For now let's focus on the "cloud computing" part rather than integer arithmetic.

2016-10-22 19:54 UTC, aaronang commented
@kc1212 I do prefer to work with `int` then; will make it much more readable.

2016-10-22 19:55 UTC, aaronang commented on lib/common.go
> +func (alph Alphabet) InitialCandidate(l int) []byte {
I see, didn't read all the reference 😛

2016-10-22 21:41 UTC, kc1212 commented
@aaronang Ok this is a bit depressing, I just converted the code to use bignum, it can convert from and to bignum. But there's one exception. If the binary is something like [1, 2, 0] base 26, the encoded bigint result is exactly the same as encoding [1, 2].

2016-10-23 17:03 UTC, victor-li approved these changes

2016-10-23 17:03 UTC, merged