Skeleton of the master
aaronang/cong-the-ripper pull request #17
Opened 2016-10-22 19:41 UTC by kc1212

Before moving ahead, it's good to have a project skeleton so that we know where to plug the features in. Some of the  of the fields in `type Master struct` is debatable, some might even be missing. But let's not dwell on those in this PR, we can update those fields as  we work on the features.

I also changed the folder structure to something more standard, so that `go build` knows what to do (before we had two packages in the same folder and `go` got confused). In fact, there's a Makefile so simply typing `make` should build everything.

I haven't looked into how to selectively run tests yet, so I commented the AWS tests for now.

2016-10-22 19:56 UTC, aaronang commented
To manually run a test you can do `go test -r TestFunction`.

2016-10-23 12:35 UTC, aaronang reviewed
Just some nitpicking. In general, it looks good to me 😄

2016-10-23 12:35 UTC, aaronang commented on lib/common.go
> +		res = res[0:l]
The `0` isn't needed right? Just nitpicking 😛

2016-10-23 12:35 UTC, aaronang commented on lib/common.go
> +	overflow := false
It would be more "Single Responsibility"-ish to have a separate function for determining the overflow/carry 😛

2016-10-23 12:35 UTC, aaronang commented on lib/common.go
>  		res[i] = Alphabets[alph][res[i]]
This for-loop can also be moved to a separate function for better SRP compliance.

2016-10-23 12:35 UTC, aaronang commented on master/job.go
>  	z = z.Add(z, big.NewInt(n))
This can be merged with its previous line right? Not sure what we like more.

2016-10-23 12:35 UTC, aaronang commented on master/master.go
> +	http.HandleFunc("/cong", m.statusHandler)
In a similar fashion, should we define these paths in lib?

2016-10-23 13:03 UTC, kc1212 commented
I think applying SRP to primitive tasks is a bit over the top. There is no limit to applying SRP if you consider everything a piece of code is doing, for example you could have
```Go
	if a == nil && b == nil {
		return true
	}
```
somewhere in your code and argue that it must go inside a function called `bothAreNil`. From my understanding of SRP from [here](https://en.wikipedia.org/wiki/Single_responsibility_principle), SRP is applied in a broader, user-facing context, e.g. on the level of public methods and packages. Furthermore the Go community doesn't value many software engineering good practices as highly as other communities, for example repeated code is pretty common in the standard library and [Rob Pike doesn't mind copying code](https://en.wikipedia.org/wiki/Code_reuse#Criticism).

2016-10-23 13:06 UTC, kc1212 commented on master/job.go
>  	z = z.Add(z, big.NewInt(n))
No, because 'z' appears twice in `z.Add(z, big.NewInt(n))`

2016-10-23 13:52 UTC, aaronang commented
@kc1212 I see. Just from my experience I find it nice to have such things separated in a function such that (1) you don't need comments to explain your code because the function name explains it and (2) it is easier to test as opposed to when you have a large method. 

I agree with your example that it is over the top to separate the logic to a function. However, I think that that kind of if-clause will consist of more if/else clauses which then might be separated in one function that contains the whole nil checking or whatever the context is. 

I guess for now it is fine to ignore SRP as the project won't be that big. For now, I approve this PR. Are we waiting for @victor-li to review this PR too?

2016-10-23 17:22 UTC, victor-li requested changes

2016-10-23 17:22 UTC, victor-li commented on master/job.go
>  	z = z.Add(z, big.NewInt(n))
So on this line, `z.Add(z, big.NewInt(n))` is sufficient. No need for the `z =`, because the result is already stored in `z` by calling `Add` on it.

2016-10-23 17:27 UTC, aaronang approved these changes
LGTM :+1:

2016-10-23 17:30 UTC, victor-li approved these changes

2016-10-23 17:30 UTC, merged