Feature/controller
aaronang/cong-the-ripper pull request #25
Opened 2016-10-27 12:21 UTC by kc1212

Some notes:
* Some of the fields are int64, I'm generating random int64s for `JobID` so that the collision is lower than simply using int. Are we ok with mixing int64s and ints? Related to #24 
* I defined slots as the "entity" that runs the tasks, i.e. slots may be empty or full, when it's full a tasks is running in the slot. I tried to be consistent in the code but may have missed some. 
* I did some simple tests on the controller, to test it fully we need the heartbeats to mutate the master struct to create variation.
* The master begins by creating a new instance, this is probably not necessary later on but it's useful for testing. The controller sees the instance but there are no tasks so it releases it afterwards.
* Haven't moved the master and slave folders to lib yet, but I will when #23 is merged.
* Some code paths are not fully tested because missing heartbeat messages. I will probably write a bit of heartbeat message handling code in the master because I'm the most familiar with it. After that, we just need the heartbeat code on the slave side from @victor-li to tie everything together (read: fix bugs). 
 
fixes #7

2016-10-27 12:30 UTC, aaronang commented
@kc1212 I think using `int` implicitly uses `int64`. In addition, the Golang tour recommends `int` unless there is a specific reason; https://tour.golang.org/basics/11.

2016-10-27 15:14 UTC, aaronang commented on master/job.go
> +	if taskSize < int64(j.Iter) {
I am confused, I thought `taskSize` indicated how many permutations a task should compute. In addition, I though that `j.Iter` indicated the number of rounds to hash a single permutation (e.g. "aaa"). If I understand it correctly, `taskSize` now indicates the number of hash computations?

2016-10-27 15:14 UTC, aaronang commented on master/job.go
> +	actualTaskSize := taskSize / int64(j.Iter)
Zero iterations doesn't make any sense, but it will be a problem if the user defines it like that.

2016-10-27 15:14 UTC, aaronang commented on master/job.go
> +	cands, lens := chunkCandidates(j.Alphabet, j.KeyLen, actualTaskSize)
`actualTaskSize` is now dependent on `j.Iter`, meaning that we are now not getting candidates of equal size _regardless_ of which job.

2016-10-27 15:14 UTC, aaronang commented on master/master.go
> +			fmt.Println(e)
Does it make sense to replace this with `log.Fatalln(e)`? Should we consider only using `log`?

2016-10-27 15:14 UTC, aaronang commented on master/master.go
> +			fmt.Println("Unable to fine public IP")
Typo

2016-10-27 15:14 UTC, aaronang commented on master/master.go
> +	// probably not necessary becase
Because?

2016-10-27 15:14 UTC, aaronang commented on master/master.go
> +		time.Sleep(10 * time.Second)
Do we call this function every time we create a slave? This will become quite a pain in the ass if we have to wait two minutes possibly for each instance.

2016-10-27 15:14 UTC, aaronang commented on master/master.go
> +type scheduler interface {
This interface isn't used anywhere anymore if I am not mistaken.

2016-10-27 15:14 UTC, aaronang commented on master/master.go
> +	http.HandleFunc(lib.JobsCreatePath, makeJobsHandler(m.jobsChan))
Would it be cleaner to also have these functions called in the HTTP goroutine?

2016-10-27 15:14 UTC, aaronang commented on master/master.go
> +	ip := getPublicIP(m.svc, s[0])
Should we do error handling here? What if we can't get the public IP in time? Do you have any other solution instead of using public IP as key?

2016-10-27 15:24 UTC, kc1212 commented on master/job.go
> +	if taskSize < int64(j.Iter) {
`taskSize` is the number of SHA2 hashes. Suppose a user submits a job using Iter = 10, and another using Iter = 100, while the other parameters are the same. Then these tasks need to be split differently. The second job will have 10 times more tasks than the first job, but each of these tasks have the same size.

2016-10-27 15:25 UTC, kc1212 commented on master/job.go
> +	actualTaskSize := taskSize / int64(j.Iter)
This can't be zero because we check for `taskSize < int64(j.Iter)`

2016-10-27 15:30 UTC, kc1212 commented on master/job.go
> +	cands, lens := chunkCandidates(j.Alphabet, j.KeyLen, actualTaskSize)
Not sure what you mean here. I explained the reasons for doing these calculations in my other comments, basically we want to make the _actual computation_ (i.e. SHA2) an invariant. Let me know if it's still not clear.

2016-10-27 15:30 UTC, kc1212 commented on master/master.go
> +type scheduler interface {
They may be caused by the merge, I'll remove it.

2016-10-27 15:31 UTC, kc1212 commented on master/master.go
> +			fmt.Println(e)
Yeah it's a good idea, we should use `log` instead of `fmt`.

2016-10-27 15:31 UTC, kc1212 commented on master/master.go
> +	// probably not necessary becase
Because the IP address should come from the heartbeat messages. I'll update the commets

2016-10-27 15:33 UTC, kc1212 commented on master/master.go
> +	ip := getPublicIP(m.svc, s[0])
When the heartbeat stuff is ready, we will populate all the slave data structures when new heartbeat arrive. So this won't be necessary. I think the http handlers can figure out the IP address.

2016-10-27 15:33 UTC, kc1212 commented on master/master.go
> +		time.Sleep(10 * time.Second)
No, this function is just there for testing, we won't need it when heartbeats are available.

2016-10-27 15:34 UTC, kc1212 commented on master/master.go
> +			fmt.Println("Unable to fine public IP")
I see...

2016-10-27 15:38 UTC, kc1212 commented on master/master.go
> +	http.HandleFunc(lib.JobsCreatePath, makeJobsHandler(m.jobsChan))
Yeah, I initially kept it outside because the handlers took pointer receiver, but they don't anymore so they can be moved inside now.

2016-10-27 15:48 UTC, kc1212 commented
Hopefully my comments and b12a79e addressed your feedback @aaronang

2016-10-27 21:08 UTC, aaronang requested changes

2016-10-27 21:08 UTC, aaronang commented on lib/master/master.go
> +		go func() {
In this case, tasks might actually be assigned to slaves that are terminated in this goroutine.

2016-10-27 21:08 UTC, aaronang commented on lib/master/master.go
> +	}
I think we also need to remove those slaves somewhere from `m.instances`.

2016-10-27 21:45 UTC, victor-li requested changes

2016-10-27 21:45 UTC, victor-li commented on lib/master/master.go
> +			// we write the status into the channel and the the handler serves the result
Typo, double `the`

2016-10-27 21:45 UTC, victor-li commented on lib/master/master.go
> +		n := -n
Golint: shadow declaration of `n` (see line 372)

2016-10-27 21:45 UTC, victor-li commented on lib/master/master.go
> +		n = n / lib.MaxSlotsPerInstance
So why not `n = -n / lib.MaxSlotsPerInstance`?

2016-10-27 21:45 UTC, victor-li commented on lib/master/master.go
> +		if n < 0 {
This case will never be `true`. Also it does not return if it ever would reach the next line.

2016-10-27 21:45 UTC, victor-li commented on lib/master/master.go
> +	cnt += len(m.newTasks)
Can be combined with the previous line

2016-10-27 21:45 UTC, victor-li commented on lib/master/master.go
> +		taskSize: 6400 * 1000 * 1000,
Did you already benchmark how long it takes for an instance to hash this amount?

2016-10-27 22:19 UTC, kc1212 commented on lib/master/master.go
> +		taskSize: 6400 * 1000 * 1000,
Nope, we'll tune this value when the system is working

2016-10-27 22:23 UTC, kc1212 commented on lib/master/master.go
> +	}
As discussed, we'll let the heartbeat handles those for now. But I'll fix the race condition.

2016-10-27 22:28 UTC, victor-li commented on lib/master/master.go
> +		e := http.ListenAndServe(m.port, nil)
`e := http.ListenAndServe(":"+m.port, nil)`

2016-10-28 08:28 UTC, kc1212 commented
@aaronang @victor-li Latest changes should address all comments

2016-10-28 09:32 UTC, aaronang submitted a review, later dismissed

2016-10-28 09:51 UTC, aaronang approved these changes

2016-10-28 09:53 UTC, merged